### ISSUE TITLE
Dialogues are ignored if there are dash (-) in the song name

### ISSUE THREAD

**Issue by aladairmaxwell** [KadeArchive/Kade-Engine#808]
If song named something like `winter-horrorland`, having `-` as a space, the dialogues just does not appear, though something simple like `philly` works perfectly fine. Is there anything I can do about it?

**Comment by isakube** [comment]
another issue with spaces

this is fixed in `master` branch

**Comment by aladairmaxwell** [comment]
I mean, I want to add my custom dialogue into custom song with spaces. But having any `-` means ignorance by the game. I'm having latest master branch.

**Comment by Lucky-56** [comment]
wait a minute, this should be fixed in master now

EDIT: oh and stable too
EDIT 2: should be fixed in Kade Engine v1.5.2

**Comment by Lucky-56** [comment]
does this still happen on v1.5.2 ?

**Comment by aladairmaxwell** [comment]
Actually, yes. I tried to add new song to Song.hx, Path.hx, PlayState.hx, FreeplayState.hx. It crashes on Story Mode with this window:

![image](https://user-images.githubusercontent.com/69295711/121677427-83470a00-cabe-11eb-8d2e-751d49e12fe1.png)

Only half of the issue were resolved. It still doesn't want to see chart files (e.g. `bfell-hard.json`) as it, but no. It tries to find `b-fell-hard.json`. Then crashes and burns due to it doesn't exist. 

I updated files like twice just to make sure it works perfectly fine. I was using latest stable branch. I can say, that Dad Battle and Philly Nice works fine with Free Mode and Story Mode, while my song can only be played in Free Mode. What did I miss? I was doing everything 1:1 as Philly Nice and Dad Battle.

**Comment by Lucky-56** [comment]
mind if I can have a look at the source code

**Comment by aladairmaxwell** [comment]
[Source.zip](https://github.com/KadeDev/Kade-Engine/files/6638642/Source.zip)
(Please don't hurt me)

**Comment by puyoxyz** [comment]
If your song name is `b fell`, it will load `b-fell`, that is what it is supposed to do, rename the charts to `b-fell`
