### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by yuh-mkv** [KadeArchive/Kade-Engine#863]
When entering the title screen, it gives a screen saying KadeEngine is on 1.5.1, and the newest is on 1.5.2, and it gives this error on both the latest stable, and latest development build.

**Comment by Lucky-56** [comment]
uhh.. this is fixed?

**Comment by yourlocalfox** [comment]
I would presume you mean in the next release because downloading from the releases page for 1.5.2 still has this issue despite the fix

**Comment by Lucky-56** [comment]
b-...   b-but

![image](https://user-images.githubusercontent.com/55949451/121954605-3e8dce00-cd5f-11eb-85ed-da6198128ec6.png)

**Comment by yourlocalfox** [comment]
I know, I know what went wrong and the problem still persisted after the supposed fix, might want to check the mainmenustate.hx file again to make sure the commit actually made it through.

**Comment by Lucky-56** [comment]
huh

**Comment by yuh-mkv** [comment]
> b-... b-but
> 
> ![image](https://user-images.githubusercontent.com/55949451/121954605-3e8dce00-cd5f-11eb-85ed-da6198128ec6.png)

it still does it after the fix

**Comment by RagdollClash** [comment]
works fine for me, downloaded it off the github release page
![2021-06-14_16-03-03_Funkin](https://user-images.githubusercontent.com/15317421/121969842-04560980-cd2a-11eb-81ab-290f59a7320f.png)

**Comment by yuh-mkv** [comment]
@Lucky-56 the commit never made it through and I had to change 1.5.1 to 1.5.2 manually

**Comment by Lucky-56** [comment]
maybe you forgot to pull
